[[constraint]]
  name = "github.com/xenserver/go-xenserver-client"
  revision = "86a0f30ec1588955b8e63b7b5ffbab43fc3a9ff1"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.28"

[[override]]
  name = "github.com/ugorji/go"
  revision = "9831f2c3ac1068a78f50999a30db84270f647af6"

[[override]]
  name = "github.com/dongyuzheng/easyssh"
  revision = "9302b2c6dc62b655f41767906ec79638db75ba40"